#!/usr/bin/env python

import sys
import json
import subprocess
import os

BUILD_ID = os.environ['BUILD_ID']
BUILD_NAME = os.environ['BUILD_NAME']
BUILD_JOB_NAME = os.environ['BUILD_JOB_NAME']
BUILD_TEAM_NAME = os.environ['BUILD_TEAM_NAME']
ATC_EXTERNAL_URL = os.environ['ATC_EXTERNAL_URL']

def err(txt):
    """Output debugging and error messages to Concourse"""
    sys.stderr.write(str(txt) + '\n')

# load in the parameters passed to the resource
parameters = json.loads(sys.stdin.read())

# source accessible with `parameters['source']`
# params accessible with `parameters['params']`

# Write your functions here...

# output version and metadata to complete the build
print(json.dumps({
    'version': {
        'ref': 'VERSION-REF'
    },
    'metadata': [
        { 'name': 'METADATA-NAME-1', 'value': 'METADATA-VALUE-1' },
        { 'name': 'METADATA-NAME-2', 'value': 'METADATA-VALUE-2' }
    ]
}))
