#!/bin/sh

set -e -u

exec 3>&1 # make stdout available as fd 3 for the result
exec 1>&2 # redirect all output to stderr for logging

source=$1

if [ -z "$source" ]; then
  echo "usage: $0 <path/to/source>" >&2
  exit 1
fi

# for jq
PATH=/usr/local/bin:$PATH

payload=$(mktemp /tmp/resource-in.XXXXXX)

# load in the parameters passed to the resource
cat > $payload <&0

# source accessible with `$(jq -r '.source // ""' < $payload)`
# params accessible with `$(jq -r '.params // ""' < $payload)`

# Write your functions here...

# output version and metadata to complete the build
jq -n "{
  version: {ref: "VERSION-REF"},
  metadata: [
    {
      name: "METADATA-NAME-1",
      value: "METADATA-VALUE-1"
    },
    {
      name: "METADATA-NAME-2",
      value: "METADATA-VALUE-2"
    }
  ]
}" >&3
